version: '3'
networks:
    database_net:
      driver: bridge
services:
  mysqldatabase:
        image: mysql:5.7
        restart: always
        environment:
               MYSQL_ROOT_PASSWORD: redhatpass
               MYSQL_USER: rahul
               MYSQL_PASSWORD: redhat
               MYSQL_DATABASE: mysqdata
        networks:
                - database_net
        volumes:
                - mysql_strg:/var/lib/mysql

  wordpress:
        image: wordpress:5.1.1-php7.3-apache
        restart: always
        depends_on:
                - mysqldatabase
        ports:
                - 8083:80
        environment:
                WORDPRESS_DB_HOST: mysqldatabase
                WORDPRESS_DB_USER: rahul
                WORDPRESS_DB_PASSWORD: redhat
                WORDPRESS_DB_NAME: mysqdata
        volumes:
                - word_press_strg:/var/www/html
        networks:
                - database_net
volumes:
    word_press_strg:
    mysql_strg:
